title: "Grünwerkatelier"
description: "Handgefertigte Yoga-Accessoires aus Thuner Gartenkräutern"

# FÜR EINE ROOT PAGE OHNE UNTERPFAD:
url: "https://gruenwerkatelier.ch"
baseurl: ""           # ⚠️ sehr wichtig, damit Jekyll nicht mehr automatisch /<reponame> davor packt

theme: minima

sass:
  style: compressed
