title: "Grünwerkatelier"
description: "Handgefertigte Yoga-Accessoires aus Thuner Gartenkräutern"

# Basis-Pfad für Project Pages
url: "https://gruenwerkatelier.ch"

# Deine Seiten-URL (für spätere Custom-Domain anpassen)
url: "https://armagnaken92.github.io"

theme: minima

sass:
  style: compressed
