title: "Grünwerkatelier"
description: "Handgefertigte Yoga-Accessoires aus Thuner Gartenkräutern"
url: "https://gruenwerkatelier.github.io"
theme: minima

# Sass/SCSS: wir legen main.scss direkt unter /assets ab
sass:
  style: compressed
