title: "Grünwerkatelier"
description: "Handgefertigte Yoga-Accessoires aus Thuner Gartenkräutern"

# Projekt-Page-Basis-URL
baseurl: "/gruenwerkatelier.github.io"
url: "https://armagnaken92.github.io"

theme: minima

sass:
  style: compressed
