title: "Gr체nwerkatelier"
description: "Handgefertigte Yoga-Accessoires aus Thuner Gartenkr채utern"
url: "https://gruenwerkatelier.github.io"
theme: minima
sass:
  sass_dir: assets/css
  style: compressed
  title: Gr체nwerkatelier
description: Handgefertigte Yoga-Accessoires aus Thuner Gartenkr채utern
